# SPDX-FileCopyrightText: 2026 Christopher Conley
# SPDX-License-Identifier: MIT

# Cross-compile to x86_64 Windows (MSVC ABI) from Linux using clang-cl + lld-link
# against an xwin-provided Windows SDK / MSVC CRT.
#
# This mirrors the project's own Windows CI job (.github/workflows/validate.yml),
# which builds with clang-cl -- so the MSVC ABI branch of every vendored header is
# the one that gets compiled, exactly as upstream intends.
#
# Prerequisites:
#   xwin splat at $ENV{XWIN_SPLAT} (default ~/.cache/xwin/splat), created with e.g.
#     xwin --accept-license splat
#   DirectX-Headers for a current d3d12.h, at $ENV{DIRECTX_HEADERS}.
#   The Windows SDK 10.0.22621 that xwin fetches predates D3D12_HEAP_TYPE_GPU_UPLOAD,
#   ID3D12Device12 and ID3D12GraphicsCommandList9, all of which plume requires.

set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR AMD64)

if (DEFINED ENV{XWIN_SPLAT})
    set(XWIN_SPLAT $ENV{XWIN_SPLAT})
else()
    set(XWIN_SPLAT "$ENV{HOME}/.cache/xwin/splat")
endif()

if (NOT EXISTS "${XWIN_SPLAT}/crt/include")
    message(FATAL_ERROR "No xwin splat at ${XWIN_SPLAT} -- set XWIN_SPLAT or run 'xwin splat'")
endif()

set(CMAKE_C_COMPILER   clang-cl)
set(CMAKE_CXX_COMPILER clang-cl)
set(CMAKE_LINKER       lld-link)
set(CMAKE_AR           llvm-lib)
set(CMAKE_RC_COMPILER  llvm-rc)
set(CMAKE_MT           llvm-mt)

set(CMAKE_C_COMPILER_TARGET   x86_64-pc-windows-msvc)
set(CMAKE_CXX_COMPILER_TARGET x86_64-pc-windows-msvc)

# System header search. /imsvc marks these as system includes so their warnings stay quiet.
set(_XWIN_INCLUDES
    "/imsvc${XWIN_SPLAT}/crt/include"
    "/imsvc${XWIN_SPLAT}/sdk/include/ucrt"
    "/imsvc${XWIN_SPLAT}/sdk/include/um"
    "/imsvc${XWIN_SPLAT}/sdk/include/shared")

# DirectX-Headers, if provided, must come first: it shadows the SDK's older <d3d12.h>.
# Prefer $DIRECTX_HEADERS, then the copy kept in this repo, then a system mingw one.
set(_DX_ROOT "")
foreach(_c "$ENV{DIRECTX_HEADERS}"
           "${CMAKE_CURRENT_LIST_DIR}/cross/directx-headers"
           "/usr/x86_64-w64-mingw32/sys-root/mingw/include")
    if (_c AND EXISTS "${_c}/directx/d3d12.h")
        set(_DX_ROOT "${_c}")
        break()
    endif()
endforeach()
if (_DX_ROOT)
    set(_DX_INCLUDES "/I${_DX_ROOT}/directx")
    message(STATUS "DirectX-Headers: ${_DX_ROOT}/directx")
else()
    message(FATAL_ERROR "No DirectX-Headers found; the xwin SDK's d3d12.h is too old")
endif()

# Case-correcting symlinks for SDK headers whose spelling in the source does not match
# the spelling on disk (Windows filesystems are case-insensitive; this one is not).
# Generated by cross/make-case-shim.sh. Must precede the real SDK dirs.
set(_CASE_SHIM "${CMAKE_CURRENT_LIST_DIR}/cross/case-shim")
if (EXISTS "${_CASE_SHIM}")
    set(_CASE_INCLUDES "/imsvc${_CASE_SHIM}")
else()
    set(_CASE_INCLUDES "")
endif()

string(JOIN " " _XWIN_CFLAGS ${_DX_INCLUDES} ${_CASE_INCLUDES} ${_XWIN_INCLUDES})

# xwin splats only the RELEASE CRT (the debug CRT is not redistributable and is a
# separate download), so every configuration must link the release runtime. Without
# this, even CMake's own compiler test asks for msvcrtd.lib and fails.
set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreadedDLL")
list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES CMAKE_MSVC_RUNTIME_LIBRARY)
set(CMAKE_C_FLAGS_DEBUG_INIT     "/Zi /Ob0 /Od")
set(CMAKE_CXX_FLAGS_DEBUG_INIT   "/Zi /Ob0 /Od")
set(CMAKE_C_FLAGS_RELEASE_INIT   "/O2 /Ob2 /DNDEBUG")
set(CMAKE_CXX_FLAGS_RELEASE_INIT "/O2 /Ob2 /DNDEBUG")

set(CMAKE_C_FLAGS_INIT   "${_XWIN_CFLAGS}")
# -Xclang -fexceptions -fcxx-exceptions matches what the Windows CI job passes.
set(CMAKE_CXX_FLAGS_INIT "${_XWIN_CFLAGS} -Xclang -fexceptions -Xclang -fcxx-exceptions")

# Case-correcting library symlinks (cross/make-case-shim.sh) and import libraries
# generated locally (cross/make-curl-implib.sh). Both must precede the SDK paths.
set(_EXTRA_LIBPATHS "")
foreach(_d "${CMAKE_CURRENT_LIST_DIR}/cross/case-shim-lib" "${CMAKE_CURRENT_LIST_DIR}/cross/winlib")
    if (EXISTS "${_d}")
        list(APPEND _EXTRA_LIBPATHS "/libpath:${_d}")
    endif()
endforeach()

set(_XWIN_LINKFLAGS
    ${_EXTRA_LIBPATHS}
    "/libpath:${XWIN_SPLAT}/crt/lib/x64"
    "/libpath:${XWIN_SPLAT}/sdk/lib/um/x64"
    "/libpath:${XWIN_SPLAT}/sdk/lib/ucrt/x64")
string(JOIN " " _XWIN_LDFLAGS ${_XWIN_LINKFLAGS})

set(CMAKE_EXE_LINKER_FLAGS_INIT    "${_XWIN_LDFLAGS}")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "${_XWIN_LDFLAGS}")
set(CMAKE_MODULE_LINKER_FLAGS_INIT "${_XWIN_LDFLAGS}")

# Host tools built for the target (rt64's file_to_c) and dxc.exe are PE binaries that
# the build must execute. Nothing registers PE in binfmt_misc here, so run them under wine.
find_program(WINE_EXECUTABLE wine)
if (WINE_EXECUTABLE)
    set(CMAKE_CROSSCOMPILING_EMULATOR ${WINE_EXECUTABLE})
endif()

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
