# SPDX-FileCopyrightText: 2026 Christopher Conley
# SPDX-License-Identifier: MIT

# Cross-compile to x86_64 Windows (MSVC ABI) from Linux using clang-cl + lld-link
# against an xwin-provided Windows SDK / MSVC CRT.
#
# This mirrors the project's own Windows CI job (.github/workflows/validate.yml),
# which builds with clang-cl -- so the MSVC ABI branch of every vendored header is
# the one that gets compiled, exactly as upstream intends.
#
# Prerequisites:
#   xwin splat at $ENV{XWIN_SPLAT}, or ~/.xwin-cache/splat, created with
#     xwin --accept-license splat
#   DirectX-Headers for a current d3d12.h, at $ENV{DIRECTX_HEADERS}.
#   The Windows SDK 10.0.22621 that xwin fetches predates D3D12_HEAP_TYPE_GPU_UPLOAD,
#   ID3D12Device12 and ID3D12GraphicsCommandList9, all of which plume requires.

set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR AMD64)

if (DEFINED ENV{XWIN_SPLAT})
    set(XWIN_SPLAT $ENV{XWIN_SPLAT})
else()
    # xwin's own default output is ./.xwin-cache/splat, relative to where it
    # was run, so `xwin --accept-license splat` from a home directory puts it at
    # ~/.xwin-cache/splat. The second path below was this file's original
    # default and was never an xwin default: it was where an unrelated
    # project's splat sat on the machine this was written on. It stays as a
    # fallback so such a splat keeps working.
    set(XWIN_SPLAT "$ENV{HOME}/.xwin-cache/splat")
    foreach(_c "$ENV{HOME}/.xwin-cache/splat" "$ENV{HOME}/.cache/xwin/splat")
        if (IS_DIRECTORY "${_c}/crt/include")
            set(XWIN_SPLAT "${_c}")
            break()
        endif()
    endforeach()
endif()

if (NOT EXISTS "${XWIN_SPLAT}/crt/include")
    message(FATAL_ERROR "No xwin splat at ${XWIN_SPLAT} -- set XWIN_SPLAT or run 'xwin splat'")
endif()

set(CMAKE_C_COMPILER   clang-cl)
set(CMAKE_CXX_COMPILER clang-cl)
set(CMAKE_LINKER       lld-link)
set(CMAKE_AR           llvm-lib)
set(CMAKE_RC_COMPILER  llvm-rc)
set(CMAKE_MT           llvm-mt)

set(CMAKE_C_COMPILER_TARGET   x86_64-pc-windows-msvc)
set(CMAKE_CXX_COMPILER_TARGET x86_64-pc-windows-msvc)

# System header search. /imsvc marks these as system includes so their warnings stay quiet.
set(_XWIN_INCLUDES
    "/imsvc${XWIN_SPLAT}/crt/include"
    "/imsvc${XWIN_SPLAT}/sdk/include/ucrt"
    "/imsvc${XWIN_SPLAT}/sdk/include/um"
    "/imsvc${XWIN_SPLAT}/sdk/include/shared")

# DirectX-Headers, if provided, must come first: it shadows the SDK's older <d3d12.h>.
# Prefer $DIRECTX_HEADERS, then the copy kept in this repo, then a system mingw one.
set(_DX_ROOT "")
foreach(_c "$ENV{DIRECTX_HEADERS}"
           "${CMAKE_CURRENT_LIST_DIR}/cross/directx-headers"
           "/usr/x86_64-w64-mingw32/sys-root/mingw/include")
    if (_c AND EXISTS "${_c}/directx/d3d12.h")
        set(_DX_ROOT "${_c}")
        break()
    endif()
endforeach()
if (_DX_ROOT)
    set(_DX_INCLUDES "/I${_DX_ROOT}/directx")
    message(STATUS "DirectX-Headers: ${_DX_ROOT}/directx")
else()
    message(FATAL_ERROR "No DirectX-Headers found; the xwin SDK's d3d12.h is too old")
endif()

# Case-correcting symlinks for SDK headers whose spelling in the source does not match
# the spelling on disk (Windows filesystems are case-insensitive; this one is not).
# Generated by cross/make-case-shim.sh. Must precede the real SDK dirs.
set(_CASE_SHIM "${CMAKE_CURRENT_LIST_DIR}/cross/case-shim")
if (EXISTS "${_CASE_SHIM}")
    set(_CASE_INCLUDES "/imsvc${_CASE_SHIM}")
else()
    set(_CASE_INCLUDES "")
endif()

string(JOIN " " _XWIN_CFLAGS ${_DX_INCLUDES} ${_CASE_INCLUDES} ${_XWIN_INCLUDES})

# xwin splats only the RELEASE CRT (the debug CRT is not redistributable and is a
# separate download), so every configuration must link the release runtime. Without
# this, even CMake's own compiler test asks for msvcrtd.lib and fails.
set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreadedDLL")
list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES CMAKE_MSVC_RUNTIME_LIBRARY)
set(CMAKE_C_FLAGS_DEBUG_INIT     "/Zi /Ob0 /Od")
set(CMAKE_CXX_FLAGS_DEBUG_INIT   "/Zi /Ob0 /Od")
set(CMAKE_C_FLAGS_RELEASE_INIT   "/O2 /Ob2 /DNDEBUG")
set(CMAKE_CXX_FLAGS_RELEASE_INIT "/O2 /Ob2 /DNDEBUG")

set(CMAKE_C_FLAGS_INIT   "${_XWIN_CFLAGS}")
# -Xclang -fexceptions -fcxx-exceptions matches what the Windows CI job passes.
set(CMAKE_CXX_FLAGS_INIT "${_XWIN_CFLAGS} -Xclang -fexceptions -Xclang -fcxx-exceptions")

# Case-correcting library symlinks (cross/make-case-shim.sh) and import libraries
# generated locally (cross/make-curl-implib.sh). Both must precede the SDK paths.
set(_EXTRA_LIBPATHS "")
foreach(_d "${CMAKE_CURRENT_LIST_DIR}/cross/case-shim-lib" "${CMAKE_CURRENT_LIST_DIR}/cross/winlib")
    if (EXISTS "${_d}")
        list(APPEND _EXTRA_LIBPATHS "/libpath:${_d}")
    endif()
endforeach()

# xwin names the x86-64 library directories "x86_64" by default and "x64"
# only when splatted with --preserve-ms-arch-notation, so probe rather than
# assume. A wrong guess here does not fail until the first link, with every
# import library reported missing at once.
function(_xwin_libdir out base)
    foreach(_a x64 x86_64)
        if (IS_DIRECTORY "${base}/${_a}")
            set(${out} "${base}/${_a}" PARENT_SCOPE)
            return()
        endif()
    endforeach()
    message(FATAL_ERROR "No x64 or x86_64 library directory under ${base}")
endfunction()

_xwin_libdir(_CRT_LIB  "${XWIN_SPLAT}/crt/lib")
_xwin_libdir(_UM_LIB   "${XWIN_SPLAT}/sdk/lib/um")
_xwin_libdir(_UCRT_LIB "${XWIN_SPLAT}/sdk/lib/ucrt")

# lld-link is case-sensitive here while MSVC was not: the SDK ships
# kernel32.Lib and CMake's implicit link set asks for kernel32.lib. xwin
# normally creates lowercase symlinks beside each library; if it was run with
# --disable-symlinks, every implicit library goes missing at the first link.
if (NOT EXISTS "${_UM_LIB}/kernel32.lib")
    message(FATAL_ERROR
        "${_UM_LIB} has no lowercase kernel32.lib. Re-run 'xwin splat' with "
        "symlinks enabled; lld-link cannot resolve the SDK's original casing.")
endif()

set(_XWIN_LINKFLAGS
    ${_EXTRA_LIBPATHS}
    "/libpath:${_CRT_LIB}"
    "/libpath:${_UM_LIB}"
    "/libpath:${_UCRT_LIB}")
string(JOIN " " _XWIN_LDFLAGS ${_XWIN_LINKFLAGS})

set(CMAKE_EXE_LINKER_FLAGS_INIT    "${_XWIN_LDFLAGS}")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "${_XWIN_LDFLAGS}")
set(CMAKE_MODULE_LINKER_FLAGS_INIT "${_XWIN_LDFLAGS}")

# Host tools built for the target (rt64's file_to_c) and dxc.exe are PE binaries that
# the build must execute. Nothing registers PE in binfmt_misc here, so run them under wine.
find_program(WINE_EXECUTABLE wine)
if (WINE_EXECUTABLE)
    set(CMAKE_CROSSCOMPILING_EMULATOR ${WINE_EXECUTABLE})
endif()

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
